#!/bin/sh

commands=('branch-check' 'lint-php' 'lint-python')

for command in ${commands[@]}; do
    sh ./.git/hooks/scripts/${command}.sh
    ret=$?
    if [ ${ret} -ne 0 ]; then
        exit 1
    fi
done
