html:
  image: busybox:glibc
  volumes:
    - ./containers/html:/www:ro
    - /etc/localtime:/etc/localtime:ro

nginx:
  build: containers/nginx
  restart: always
  ports:
    - "8080:80"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - html
